version: '3.4'

services:
  g64.pedidoapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: g64soat
      MYSQL_DATABASE: G64SOATPedido
    ports:
      - "3307:3307"
  #check-connection:
  #  image: mysql:latest
  #  command: sh -c "app-get update && apt-get install"
  #  depends_on:
  #    - mysql
volumes: 
  mysql_data: