version: '3.9'
volumes:
    datafiles:

services:
  db:
    image: mysql:8.0.0
    volumes:
      - datafiles:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: g64soat
    
  pedidoapi:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DBHOST=db
    entrypoint: ["dotnet", "G64.PedidoAPI.dll"]
